### ISSUE TITLE
Better support for numpy-style docstrings

### ISSUE THREAD

**Issue by DerWeh** [heavenshell/vim-pydocstring#43] opened 2018-01-15 21:19 UTC
First thanks for the great plug-in, it really improves my code quality.
However, it sadly doesn't sufficiently support `numpy-style` docstrings. Or at least I am too stupid to configure it properly.  
So far I look into the examples in the `test` directory and played around, but it either works for annotated arguments, or arguments which are not annotated, never for both.
What I optimally want is:

```
"""
_header_.

Parameters
---------------
_arg_name_  : {opt _type_}
    _arg_name_ is

Returns
----------
_header_ : {opt _return_type_}
"""
```

The problems I face:

* I can't combine the `{{_header_}` with the `{{_return_type_}}` keyword (really minor problem, using `returnVar` instead is not all that bad
* The structure for the arguments works either 
  * for not annotated arguments  `
{{_args_}} : {{_lf_}}{{_nested_indent_}}{{_args_}} is` in `multiline`; `{{_name_}} : {{_type_}}` in `arg`
  * for annotated arguments `{{_args_}} : {{_type_}}{{_lf_}}{{_nested_indent_}}{{_name_}} is` in `arg`; `{{_args_}}` in `mutliline`

I think making `{{_name_}}` (maybe as `_arg_name`?) and `{{_type_}}` (as `_arg_type`?) available in `multiline` should solve the second problem.

**Comment by heavenshell** [comment] 2018-01-16 12:20
@DerWeh Sorry for the inconvenience.
I'm sorry I don't understand your problem.

Could you show me method/function signature, actual behaveior and excepted output?

**Comment by DerWeh** [comment] 2018-01-17 23:27
@heavenshell sorry for not being clear enough. The actual behavior is of course hard to explain as it depends on your templates. What I want is more clearly:

```python
def func(a: int, b, c):
    """
    func.
    
    Parameters
    ----------
    a : int
        a is
    b :
        b is
    c :
        c is

    Returns
    -------
    func :
    
    """"


def func2(a: int, b, c) -> double:
    """
    func2.
    
    Parameters
    ----------
    a : int
        a is
    b :
        b is
    c :
        c is

    Returns
    -------
    func2 : double

    """
```
My problem is that I know who to make it work without annotations

```
    b :
        b is
```

or with annotations

```
    a : int
        a is
```

but I am not able to write a template working with both. Also there seems to be no way to use `{{_header_}}` and `{{_return_type_}}` on the same line to get the desired output for `Returns`.

**Comment by heavenshell** [comment] 2018-01-18 17:27
@DerWeh 
Sorry for my poor english 😰 

> What I want is more clearly

I think your example is expected behavior.
https://github.com/heavenshell/vim-pydocstring/blob/master/test/numpy-template.vader#L50-L62

>My problem is that I know who to make it work without annotations

```
    b :
        b is
```
`b` does not have any type hint at signature. So pydocstring.vim can't generate type.

I think I still did not understand your problem. I'm sorry...


>Also there seems to be no way to use {{_header_}} and {{_return_type_}} on the same line to get the desired output for Returns.

Yes, this is current spec.
If you have return type hint, replace `{{_return_type_}}` to type.
If you don't have return type, nothing to replace, because pydocstring.vim don't know what type should generate.

**Comment by heavenshell** [comment] 2018-03-28 11:46
No progress. so I close this.

**Closed by heavenshell** 2018-03-28 11:46 UTC
